Update compile - reduce node_modules size

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -75,7 +75,13 @@ has_build_script=$(has_script "package.json" "build")
 if [[ "$has_build_script" == "true" && ! -f .skip-bun-build ]]; then
   echo "Building application..."
   bun run build || { echo "Build failed"; exit 1; }
-  echo "Done building application..."
+  echo "Done building application."
+  echo " "
+  echo "Removing dependencies..."
+  rm -rf node_modules/
+  echo "Running 'bun i --production'"
+  bun install --production || { echo "Production packages installation failed"; exit 1; }
+  echo "Done installing production packages."
 fi
 
 # Postbuild
